apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
    name: demo-application
    namespace: argocd
spec:
    project: default
    source:
        repoURL: https://github.com/jaseemjaskp/argocd-app-config.git
        targetRevision: HEAD
        path: dev
    destination:
        - server: https://kubernetes.default.svc
          namespace: demo-agocd-apps
    clusterResourceWhitelist:
        - group: ''
            kind: Namespace
        - group: 'rbac.authorization.k8s.io'
            kind: ClusterRole
        - group: 'rbac.authorization.k8s.io'
            kind: ClusterRoleBinding
        - group: 'policy'
            kind: PodSecurityPolicy
        - group: 'apiextensions.k8s.io'
            kind: CustomResourceDefinition
        - group: 'pkg.crossplane.io'
            kind: Configuration
        - group: 'pkg.crossplane.io'
            kind: Lock
        - group: 'pkg.crossplane.io'
            kind: Provider
        - group: 'aws.crossplane.io'
            kind: ProviderConfig
        - group: 'eks.sarathy.io'
            kind: EKSCluster
        - group: 'eks.aws.crossplane.io'
            kind: NodeGroup
        - group: 'eks.aws.crossplane.io'
            kind: Cluster
        - group: 'ec2.aws.crossplane.io'
            kind: Subnet
        - group: 'ec2.aws.crossplane.io'
            kind: RouteTable
        - group: 'ec2.aws.crossplane.io'
            kind: SecurityGroup
        - group: 's3.aws.upbound.io'
            kind: Bucket              
    syncPolicy: 
        syncOptions:
            - CreateNamespace=true
        
        automated:
            selfHeal: true
            prune: true